masonry/plugins/cornerstone/grails-app/domain/com/cloudmasons/Theme.groovy
package com.cloudmasons

public class Theme {

    public static DEFAULT_THEME = new Theme(
            name: 'default', 
            description: 'The default cloudmasons theme',
            layout: 'main',
            plugin: 'cornerstone');
    
    String name
    
    String description

    String layout = 'main'
    
    String editPropertyPath = 'bean/edit'
    String showPropertyPath = 'bean/show'
    String printPropertyPath = 'bean/print'
    
    /** Themes can extend one another **/
    Theme parent
    
    // Theme is passed into the template resolver which
    // uses property path to find property templates.
    String propertyPath = editPropertyPath
    
    /** 
     * The name of the plugin containing the default
     * templates for the theme
     */
    String plugin = 'cornerstone'
    
    
    static transients = [ 'propertyPath']
    
    static mapping = {
       cache true
    }
    static constraints = {
        name(summary: true)
        description(nullable: true, summary: true)
        parent(nullable: true)
        plugin(nullable: true)
    }
    
}

masonry/plugins/cornerstone/grails-app/controllers/com/cloudmasons/cornerstone/SecureFileController.groovy
package com.cloudmasons.cornerstone

import grails.converters.JSON
import com.cloudmasons.BeanUtils


/**
 * 
 */
class SecureFileController {
    def grailsApplication
    def secureFileService
    
    // create a progress object on the session..
    def upload = {
        println params

        def downloadedfile = request.getFile('Filedata');
        def filename = params.Filename
        downloadedfile.transferTo(new File("/tmp/${filename}"))
        def model = [name: filename,
                     originalFilename: filename,
                     description: filename,
                     size:downloadedfile.getSize(),
                     storageType: 'LOCAL',
                     encryptedName: filename,
                     encryptedSize: downloadedfile.getSize(),
                     encryptionKey: 'asdfasdf',
                     path: '/tmp/',
                     secondaryStorageType: 'S3',
                     secondaryPath: 'bucket1234',
                     status: 'COPY_TO_SECONDARY']
                     
        render model as JSON
    }

    def download = {
        def domainClass = BeanUtils.resolveDomainClass(grailsApplication, params.beanClass)
        if (!domainClass) {
            if (params.errorController && params.errorAction) {
               flash.message = "Unable to find secure file class for ${attrs.beanType}"
               redirect controller: params.errorController, action: params.errorAction
            }
            else {
                def model = [error:"Unable to find secure file class for ${attrs.beanType}"]
                render model as JSON
            }
           return
        }
        
        def bean = domainClass.clazz.get(params.id)
        if (!bean) {
           if (params.errorController && params.errorAction) {
               flash.message = "Unable to find secure file for ${attrs.beanType}:${params.id}"
               redirect controller: params.errorController, action: params.errorAction
           }
           else {
               def model = [error:"Unable to find secure file for ${attrs.beanType}:${params.id}"]
               render model as JSON
           }
           return
        }
        //bean.downloads++
        //bean.save()
        def inputStream = secureFileService.getInputStream(bean)
        if (inputStream != null) {
            def originalFileName = bean.originalFilename.encodeAsURL()
            def contentDisposition = params.contentDisposition ?: 'attachment'
            response.setContentType('application/octet-stream')
            response.setHeader("Content-disposition", "${contentDisposition}; filename=${originalFileName}")
            response.outputStream << inputStream
            return
        } else {
            if (params.errorController && params.errorAction) {
                flash.message = "Unable to find file"
                redirect controller: params.errorController, action: params.errorAction
            }
            else {
                def model = [error:"Unable to find file"]
                render model as JSON
            }
            return
        }
    }
}

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/BigDecimal.gsp
<g:if test="${cp.inList}">
   <%
       String noSelection = ''
       if (field.optional) {
          if (field.manyToOne || field.oneToOne) {
                noSelection = "noSelection=\"['null': '']\""
            }
            else {
                noSelection = "noSelection=\"['': '']\""
            }
        }
   %>
   <g:select name="${beanPath}" from="${cp.inList}" value="${fieldValue(bean: bean, field: field.name)}" valueMessagePrefix="${field.domainClass.propertyName}.${field.name}" ${noSelection} />
</g:if>
<g:else>
   <input class="txt${ error ? ' error' : ''} money" type="text" id="${beanPath}" name="${beanPath}" size="30" value="${fieldValue(bean: bean, field: field.name)}" />
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/Boolean.gsp
<g:checkBox class="check" name="${beanPath}" value="${value}" />

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/Collection.gsp
<!-- Used by logic in the update processing to not accidently remove a field -->
<%
  // Honor the allowedValues constraint
  def values = []
  def allowedValues = cp?.getAppliedConstraint('allowedValues')
  if (allowedValues) {
      values = allowedValues.getValues(bean)
  } else {
      values = field.referencedDomainClass.clazz.list()
  }
  values = values?.sort { it.name }
 %>
<g:hiddenField name="${beanPath}Present" value="true" />
<g:select name="${beanPath}" from="${values}" multiple="yes" optionKey="id" optionValue="name" size="5" value="${value}" />

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/Date.gsp
<%
   def format = cp?.format ?: message(code: 'default.edit.date.format', default: 'MM/dd/yyyy')
   
   def closure = domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.defaultValue
   if (!value && closure) {
      closure.resolveStrategy = Closure.DELEGATE_FIRST 
      closure.delegate = beanInstance
      value = closure();
   }
   def readonly = ''
   def dateClass = 'date'
   if (domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.readOnly) {
        readonly = 'readonly'
        dateClass = ''
   }
%>
<input ${readonly} class="${dateClass} txt" type="text" name="${beanPath}" id="${beanPath}" value="${value?.format(format)}"/>
<g:if test="${required}">
    <font color="red"> *</font>
</g:if>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/Object.gsp

${value?.toString()}

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/String.gsp
    <%
       String renderClass = ''
       String size='30'
       if (domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.timepicker) {
          renderClass = 'time'
          size=null
       }
        
       def closure = domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.defaultValue
       if (!value && closure) {
          closure.resolveStrategy = Closure.DELEGATE_FIRST 
          closure.delegate = beanInstance
          value = closure();
       }
       def readonly = ''
       if (domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.readOnly) {
            readonly = 'readonly'
       }
      
    %>
<g:if test="${cp?.inList}">
    <g:select name="${beanPath}" from="${cp.inList.sort()}" value="${fieldValue(bean: bean, field: property.name)}" valueMessagePrefix="${field.domainClass.propertyName}.${field.name}" noSelection="['': 'select...']" />
</g:if>
<g:elseif test="${'textarea' == cp?.widget || (cp?.maxSize > 250 && !cp?.password && !cp?.inList)}">
    <g:if test="${readonly}">
        <g:textArea readonly="readonly" id="${beanPath}" name="${beanPath}" cols="60" rows="5" value="${value}" />
    </g:if>
    <g:else>
        <g:textArea  id="${beanPath}" name="${beanPath}" cols="60" rows="5" value="${value}" />
    </g:else>
</g:elseif>
<g:elseif test="${cp?.password  == true}">
   <input ${readonly} class="txt ${g.hasErrors(bean:bean, field: property.name, 'error')}"  type="password" id="${beanPath}" name="${beanPath}" size="30" value="shhhhhsecret" />
   <g:if test="${required}">
    <font color="red"> *</font>
   </g:if>
</g:elseif>
<g:else>
   <input ${readonly} class="${renderClass} txt ${g.hasErrors(bean:bean, field: property.name, 'error')}" type="text" id="${beanPath}" name="${beanPath}" size="${size}" value="${value}" />
   <g:if test="${required}">
    <font color="red"> *</font>
   </g:if>
</g:else>


masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/manyToManyCollection.gsp
<!-- Used by logic in the update processing to not accidently remove a field -->
<%
  // Honor the allowedValues constraint
  def values = []
  def allowedValues = cp?.getAppliedConstraint('allowedValues')
  if (allowedValues) {
      values = allowedValues.getValues(bean)
  } else {
      values = field.referencedDomainClass.clazz.list()
  }
  values = values?.sort { it.name }
 %>
<g:hiddenField name="${beanPath}Present" value="true" />
<g:select name="${beanPath}" from="${values}" multiple="yes" optionKey="id" optionValue="name" size="5" value="${value}" />

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/manyToManyObject.gsp
<!-- Used by logic in the update processing to not accidently remove a field -->
<g:hiddenField name="${beanPath}Present" value="true" />
<g:select name="${beanPath}" from="${property.referencedDomainClass.clazz.list()}" multiple="yes" optionKey="id" optionValue="name" size="5" value="${value}" />

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/manyToOneObject.gsp
<%
  // Honor the allowedValues constraint
  def values = []
  def allowedValues = cp?.getAppliedConstraint('allowedValues')
  if (allowedValues) {
      values = allowedValues.getValues(bean)
  } else {
      values = field.referencedDomainClass.clazz.list()
  }
  values = values.sort { it.name }

  def names = values.collect { it.name; }
  def labels = []
  def keys = []
  values?.each { v ->
    if (names.count(v.name) > 1 ) {
        labels.add("${v.name} - ${v.description ?: 'no description'}");
    } else {
        labels.add(v.name);
    }
    keys.add(v.id);
  }
 %>
<g:if test="${field.optional}">
   <g:if test="${field.manyToOne || field.oneToOne}">
      <g:select name="${beanPath}.id" from="${labels}" keys="${keys}" value="${value?.id}" noSelection="['null': 'select...']" />
   </g:if>
   <g:else>
      <g:select name="${beanPath}.id" from="${labels}" keys="${keys}" value="${value?.id}" noSelection="['': 'select...']" />
   </g:else>
</g:if>
<g:else>
   <g:select name="${beanPath}.id" from="${labels}" keys="${keys}" value="${value?.id}" ${noSelection} />
</g:else>


masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/oneToManySecureFile-old.gsp
<%-- Generate the dialog for editing each of the properties --%>
<g:each in="${value}" status="i" var="b">
     <div id="modified-${domainClass.propertyName}-edit-${property.name}-form-${i}">
     
     </div>
   <div id="dialog-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="Edit ${property.referencedDomainClass.naturalName}">
        <theme:propertyGroup bean="${b}"  beanPathPrefix="${property.name}[${i}]." />
   </div>
</g:each>

<table class="compact">
  <tbody>
    <g:each in="${value}" status="i" var="f">
      <tr class="${domainClass.propertyName}-edit-${property.name}-form-${i}">
        <td><g:link controller="secureFile" action="download" id="${f.id}" params="[beanClass: property.referencedDomainClass.name]">${f.name}</g:link>
        </td>
        <td>
           <a class="ico show-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="edit"><img src="${resource(dir:'css/boxie/img/led-ico',file:'pencil.png')}" alt="edit" />Edit</a> |
           <a class="ico delete-${domainClass.propertyName}-edit-${property.name}-form-${i}" href="#" id="delete-${property.name}-${i}" title="delete"><img src="${resource(dir:'css/boxie/img/led-ico',file:'delete.png')}" alt="delete" />Delete</a>
        </td>
      </tr>
     </g:each>
   </tbody>
</table>

<br/>
<p>New Files:
<p><i>note: ${domainClass.naturalName} must be saved before new files are available for download.</i>
<script type="text/javascript">
$(document).ready(function() {
    $("#uploadify").uploadify({
        'uploader'       : "${resource(dir: 'upload', file:'uploadify.swf', plugin:'cornerstone', absolute: true)}",
        'script'         : "${createLink(controller: 'secureFile', action:'upload', absolute: true)}",
        'cancelImg'      : "${resource(dir: 'upload', file:'cancel.png', plugin:'cornerstone', absolute: true)}",
        'folder'         : 'uploads',
        'queueID'        : 'fileQueue',
        'buttonText'     : 'Upload Files',
        'auto'           : true,
        'multi'          : true,
        'scriptData'     : {'jsessionid': '${g.cookie(name: 'JSESSIONID')}'},
        'onComplete'     : function(event, ID, fileObj, response, data) {
                               alert('response' + response);
                               responseData = jQuery.parseJSON(response)
                               var offsetStr = $('#numberOfSecureFiles').val()
                               var offset = parseInt(offsetStr)
                               var secureFile = '<p><b>'+responseData.name+'</b> pending save </p>';

                               for (var key in responseData) {
                                  secureFile = secureFile + '<input type="hidden" name="${property.name}['+offset+'].' + key + '" value="'+responseData[key]+'" />';
                               }
                               $('#secureFiles').append(secureFile);
                               $('#numberOfSecureFiles').val(offset + 1 )
                               return true;
                            }
    });
    setupOneToMany('${domainClass.propertyName}', '${property.name}', ${value ? value.size() : 0}) 

});


</script>

<g:hiddenField id="numberOfSecureFiles" name="numberOfSecureFiles" value="${value ? value.size() : 0}" />
<input type='hidden' autocomplete="off" id='removeFrom${property.name}' name='removeFrom${property.name}' />

<div id="secureFiles">

</div>
<div id="fileQueue"></div>
<input type="file" class="uploadify" name="uploadify" id="uploadify" />
<p><a href="javascript:jQuery('#uploadify').uploadifyClearQueue()">Cancel All Uploads</a></p>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/oneToManySecureFile.gsp
<%-- Generate the dialog for editing each of the properties --%>
<g:each in="${value}" status="i" var="b">
     <div id="modified-${domainClass.propertyName}-edit-${property.name}-form-${i}">
     
     </div>
   <div id="dialog-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="Edit ${property.referencedDomainClass.naturalName}">
        <theme:propertyGroup bean="${b}" props="${['name', 'description']}"  beanPathPrefix="${property.name}[${i}]." />
   </div>
</g:each>

<table class="compact">
  <tbody>
    <g:each in="${value}" status="i" var="f">
      <tr class="${domainClass.propertyName}-edit-${property.name}-form-${i}">
        <td><g:link controller="secureFile" action="download" id="${f.id}" params="[beanClass: property.referencedDomainClass.name]">${f.name}</g:link>
        </td>
        <td>
           <a class="ico show-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="edit"><img src="${resource(dir:'css/boxie/img/led-ico',file:'pencil.png')}" alt="edit" />Edit</a> |
           <a class="ico delete-${domainClass.propertyName}-edit-${property.name}-form-${i}" href="#" id="delete-${property.name}-${i}" title="delete"><img src="${resource(dir:'css/boxie/img/led-ico',file:'delete.png')}" alt="delete" />Delete</a>
        </td>
      </tr>
     </g:each>
   </tbody>
</table>

<br/>
<p>New Files:
<p><i>note: ${domainClass.naturalName} must be saved before new files are available for download.</i>
<script type="text/javascript">
$(document).ready(function() {
    $("#uploadify").uploadify({
        'uploader'       : "${resource(dir: 'upload', file:'uploadify.swf', plugin:'cornerstone', absolute: true)}",
        'script'         : "${createLink(controller: 'secureFile', action:'upload', absolute: true)}",
        'cancelImg'      : "${resource(dir: 'upload', file:'cancel.png', plugin:'cornerstone', absolute: true)}",
        'folder'         : 'uploads',
        'queueID'        : 'fileQueue',
        'buttonText'     : 'Upload Files',
        'auto'           : true,
        'multi'          : true,
        'scriptData'     : {'jsessionid': '${g.cookie(name: 'JSESSIONID')}'},
        'onComplete'     : function(event, ID, fileObj, response, data) {
                               responseData = jQuery.parseJSON(response)
                               var offsetStr = $('#numberOfSecureFiles').val()
                               var offset = parseInt(offsetStr)
                               var secureFile = '<p><b>'+responseData.name+'</b> pending save </p>';

                               for (var key in responseData) {
                                  secureFile = secureFile + '<input type="hidden" name="${property.name}['+offset+'].' + key + '" value="'+responseData[key]+'" />';
                               }
                               $('#secureFiles').append(secureFile);
                               $('#numberOfSecureFiles').val(offset + 1 )
                               return true;
                            }
    });
    setupOneToMany('${domainClass.propertyName}', '${property.name}', ${value ? value.size() : 0});
});


</script>

<g:hiddenField id="numberOfSecureFiles" name="numberOfSecureFiles" value="${value ? value.size() : 0}" />
<input type='hidden' autocomplete="off" id='removeFrom${property.name}' name='removeFrom${property.name}' />

<div id="secureFiles">

</div>
<div id="fileQueue"></div>
<input type="file" class="uploadify" name="uploadify" id="uploadify" />
<p><a href="javascript:jQuery('#uploadify').uploadifyClearQueue()">Cancel All Uploads</a></p>

    

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/oneToOneObject.gsp
<%
  // Honor the allowedValues constraint
  def values = []
  def allowedValues = cp?.getAppliedConstraint('allowedValues')
  if (allowedValues) {
      values = allowedValues.getValues(bean)
  } else {
      values = field.referencedDomainClass.clazz.list()
  }
  values = values.sort { it.name }

  def names = values.collect { it.name; }
  def labels = []
  def keys = []
  values?.each { v ->
    if (names.count(v.name) > 1 ) {
        labels.add("${v.name} - ${v.description ?: 'no description'}");
    } else {
        labels.add(v.name);
    }
    keys.add(v.id);
  }
 %>
<g:if test="${field.optional}">
   <g:if test="${field.manyToOne || field.oneToOne}">
      <g:select name="${beanPath}.id" from="${labels}" keys="${keys}"  value="${value?.id}" noSelection="['null': 'select...']" />
   </g:if>
   <g:else>
      <g:select name="${beanPath}.id" from="${labels}" keys="${keys}"  value="${value?.id}" noSelection="['': 'select...']" />
   </g:else>
</g:if>
<g:else>
   <g:select name="${beanPath}.id" from="${labels}" keys="${keys}"  value="${value?.id}" ${noSelection} />
</g:else>


masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/propertyGroup.gsp
                            <fieldset>
                             <g:if test="${title}">
                               <legend>${title}</legend>
                             </g:if>
                             <table>
                               <g:each in="${properties}" var="${property}" status="i">
                                 <%
                                    def propertyLabel = g.message(code: "${domainClass.propertyName}.${property.name}.label", default: property.naturalName)
                                 %>
                               <g:if test="${domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.longLabel}">
                                   <tr>
                                        <td align="left" style="vertical-align: top;" colspan="2">
                                           <g:if test="${!(property.oneToMany && property.bidirectional)}"> <%-- Hide the label on what is usually a table for one-to-many --%>
                                              <label class="${g.hasErrors(bean:bean, field: property.name, 'error')} "for="${property.name}">
                                                <g:if test="${domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.labelOnly}">
                                                    <b><bean:label bean="${bean}" property="${property}"/>:</b>
                                                </g:if>
                                                <g:else>
                                                    <bean:label bean="${bean}" property="${property}"/>:
                                                </g:else>
                                              </label>
                                           </g:if>
                                        </td>
                                   </tr>
                                   <g:if test="${!domainClass?.constrainedProperties[property.name]?.getAppliedConstraint('renderOptions')?.renderOptions?.labelOnly}">
                                   <tr>
                                        <td align="left" style="vertical-align: top;" colspan="2"><theme:property bean="${bean}" beanPathPrefix="${beanPathPrefix}" name="${property.name}"/></td>
                                        
                                   </tr>
                                   </g:if>
                                   <tr>
                                        <td align="left" style="vertical-align: top;" colspan="2"><br/></td>
                                   </tr>
                               </g:if>
                               <g:else>
                                <tr>
                                    <td align="right" style="vertical-align: top;">
                                       <g:if test="${!(property.oneToMany && property.bidirectional)}"> <%-- Hide the label on what is usually a table for one-to-many --%>
                                          <label class="${g.hasErrors(bean:bean, field: property.name, 'error')} "for="${property.name}"><bean:label bean="${bean}" property="${property}"/>:</label>
                                       </g:if>
                                    </td>
                                    <td nowrap="true" style="white-space: nowrap;"><theme:property bean="${bean}" beanPathPrefix="${beanPathPrefix}" name="${property.name}"/></td>
                                </tr>
                               </g:else>
                                </g:each>
                              </table>
                            </fieldset>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/edit/propertyGroups.gsp

<g:each in="${propertyGroups.keySet()}" var="${group}" status="i">
    <b>${group}</b>
    <theme:propertyGroup bean="${bean}" name="${group}" beanPathPrefix="${beanPathPrefix}" props="${propertyGroups[group]}" />
    <br/>
</g:each>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/Boolean.gsp
<g:if test="${value != null}">
<%
   if (value) {
     out << message(code: 'default.true.display', default: 'yes')
   } else {
     out << message(code: 'default.false.display', default: 'no')
   }
%>
</g:if>
<g:else>
<i>no value</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/Collection.gsp
<g:if test="${value}">
<g:each in="${value}" status="idx" var="${val}">
    ${val}<br/>
</g:each>
</g:if>
<g:else>
<i>none</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/Date.gsp
<%
   def format = cp?.format ?: message(code: 'default.date.format', default: 'MM/dd/yyyy')
%>
<g:if test="${value != null}">
${value?.format(format)}
</g:if>
<g:else>
<i>no value</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/Object.gsp
<g:if test="${value != null}">
  <g:if test="${cp?.password  == true}">
    ****************
  </g:if>
  <g:else>
    ${fieldValue(bean: bean, field: field.name)}
  </g:else>
</g:if>
<g:else>
<i>no value</i>
</g:else>


masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/String.gsp
<g:if test="${value != null}">
  <g:if test="${cp?.password  == true}">
    ****************
  </g:if>
  <g:else>
    <theme:renderHTML value="${value}"/>
  </g:else>
</g:if>
<g:else>
<i>no value</i>
</g:else>


masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/manyToManyCollection.gsp
<g:if test="${value}">
<g:each in="${value}" status="idx" var="${val}">
    ${val}<br/>
</g:each>
</g:if>
<g:else>
<i>none</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/manyToManyObject.gsp
<g:if test="${value != null}">
${value?.join(', ')?.encodeAsHTML()}
</g:if>
<g:else>
<i>none</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/manyToOneObject.gsp
<g:if test="${value != null}">
${value?.name?.encodeAsHTML()}
</g:if>
<g:else>
<i>none</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/oneToManyObject.gsp

<g:if test="${value}">
    <%-- Generate the summary table the items --%>
    <table class="compact">
      <thead>
        <tr>
       <% summaryProperties.eachWithIndex { p, i ->
          if (i < 6) { %>
                 <th><bean:label bean="${property.referencedDomainClass?.newInstance()}" property="${p}"/></th>
       <% } } %>
              <th>Actions</th>
        </tr>  
      </thead>
      
      <tbody>
        <g:each in="${value}" status="i" var="bean">
           <tr>
             <%  
              summaryProperties.eachWithIndex { p, j ->
                 out << "<td>"
                 out << theme.property(bean:bean, beanPathPrefix:beanPathPrefix, name:p.name, readonly:true)
                 out << "</td>"
             
              } %>
                <td class="tc">
                  <a  class="ico show-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="view item">View</a>
                </td>
           </tr>
        </g:each>
     
      <tbody>
      <tfoot>
      </tfoot>
      
    </table>
 
  <g:each in="${value}" status="i" var="b">
   <div id="dialog-${domainClass.propertyName}-edit-${property.name}-form-${i}" title="Show  ${property.referencedDomainClass.naturalName}">
        <theme:propertyGroups bean="${b}" readonly="${true}"/>
   </div>
  </g:each>

  <script type="text/javascript">
    $(document).ready(function() {
      setupOneToMany('${domainClass.propertyName}', '${property.name}', ${value ? value.size() : 0}) 
    });
  </script>
</g:if>
<g:else>
  <i>No ${property.name} for this ${domainClass.naturalName}</i>
</g:else>



masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/oneToManySecureFile.gsp
<g:if test="${value}">
    <table class="compact">
      <thead>
        <tr>
          <th>File</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>  
      </thead>
    
      <tbody>
        <g:each in="${value}" status="i" var="f">
          <tr>
            <td><g:link controller="secureFile" action="download" id="${f.id}" params="[beanClass: property.referencedDomainClass.name]">${f.name}</g:link>
            </td>
            <td><g:link controller="secureFile" action="download" id="${f.id}" params="[beanClass: property.referencedDomainClass.name]">${f.description}</g:link>
            </td>
            <td><g:link controller="secureFile" action="download" id="${f.id}" params="[beanClass: property.referencedDomainClass.name]">[download]</g:link>
            </td>
          </tr>
         </g:each>
       </tbody>
    </table>
</g:if>
<g:else>
  <i>No files are attached to this ${domainClass.naturalName}</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/oneToOneObject.gsp
<g:if test="${value != null}">
    <g:if test="${beanControllerName != property.name && property.otherSide}">
        <g:link controller="${beanControllerName}" action="show" id="${beanInstance?.id}" params="[associated: property.name, propertyId: value?.id]">${value?.name}</g:link>
    </g:if>
    <g:else>
        ${value?.name?.encodeAsHTML()}
    </g:else>
</g:if>
<g:else>
<i>none</i>
</g:else>

masonry/plugins/cornerstone/grails-app/views/theme/default/bean/show/propertyGroups.gsp

<g:each in="${propertyGroups.keySet()}" var="${group}" status="i">
    <b>${group}</b>
    <theme:propertyGroup bean="${bean}" name="${group}" beanPathPrefix="${beanPathPrefix}" props="${propertyGroups[group]}" readonly="${true}"/>
    <br/>
</g:each>

masonry/plugins/cornerstone/grails-app/views/theme/default/messages.gsp
        <g:if test="${flash.message}">
            <div class="msg msg-ok">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${bean}">
            <div class="msg msg-error">
                <g:renderErrors bean="${bean}" as="list" />
            </div>
        </g:hasErrors>

masonry/plugins/cornerstone/grails-app/views/theme/default/panel.gsp
 <div class="box box-${width} altbox">
   <div class="boxin">
      <%
      
      out << body()
      
      %>
   </div>
 </div>